"""empty message

Revision ID: 07aa931177c0
Revises: 42685afcf868
Create Date: 2023-03-14 23:19:51.552510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07aa931177c0'
down_revision = '42685afcf868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('article_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint('author_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('author_user_id_fkey', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('article_author_id_fkey', 'author', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
