"""empty message

Revision ID: 42685afcf868
Revises: e99aa3514d03
Create Date: 2023-03-14 22:17:36.663554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42685afcf868'
down_revision = 'e99aa3514d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('article_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint('author_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('author_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('article_author_id_fkey', 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###
