"""empty message

Revision ID: 50064e467d07
Revises: 07aa931177c0
Create Date: 2023-03-14 23:25:50.178741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50064e467d07'
down_revision = '07aa931177c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
